package hgeosec;
// Generated 28-sep-2013 22:15:52 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Incidente generated by hbm2java
 */
public class Incidente  implements java.io.Serializable {


     private Integer id;
     private Tipocoordenada tipocoordenada;
     private String latitud;
     private String longitud;
     private String descripcion;
     private Date fechareporte;
     private Date fechaincidente;
     private byte estado;

    public Incidente() {
    }

	
    public Incidente(Tipocoordenada tipocoordenada, String latitud, String longitud, Date fechareporte, Date fechaincidente, byte estado) {
        this.tipocoordenada = tipocoordenada;
        this.latitud = latitud;
        this.longitud = longitud;
        this.fechareporte = fechareporte;
        this.fechaincidente = fechaincidente;
        this.estado = estado;
    }
    public Incidente(Tipocoordenada tipocoordenada, String latitud, String longitud, String descripcion, Date fechareporte, Date fechaincidente, byte estado) {
       this.tipocoordenada = tipocoordenada;
       this.latitud = latitud;
       this.longitud = longitud;
       this.descripcion = descripcion;
       this.fechareporte = fechareporte;
       this.fechaincidente = fechaincidente;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipocoordenada getTipocoordenada() {
        return this.tipocoordenada;
    }
    
    public void setTipocoordenada(Tipocoordenada tipocoordenada) {
        this.tipocoordenada = tipocoordenada;
    }
    public String getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(String latitud) {
        this.latitud = latitud;
    }
    public String getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(String longitud) {
        this.longitud = longitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechareporte() {
        return this.fechareporte;
    }
    
    public void setFechareporte(Date fechareporte) {
        this.fechareporte = fechareporte;
    }
    public Date getFechaincidente() {
        return this.fechaincidente;
    }
    
    public void setFechaincidente(Date fechaincidente) {
        this.fechaincidente = fechaincidente;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


