package hgeosec;
// Generated 28-sep-2013 22:15:52 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipocoordenada generated by hbm2java
 */
public class Tipocoordenada  implements java.io.Serializable {


     private Integer tipo;
     private String descripcion;
     private boolean estado;
     private Set<Incidente> incidentes = new HashSet<>(0);

    public Tipocoordenada() {
    }

	
    public Tipocoordenada(String descripcion, boolean estado) {
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Tipocoordenada(String descripcion, boolean estado, Set<Incidente> incidentes) {
       this.descripcion = descripcion;
       this.estado = estado;
       this.incidentes = incidentes;
    }
   
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set<Incidente> getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Set<Incidente> incidentes) {
        this.incidentes = incidentes;
    }




}


